#pragma once

#define WIN32_LEAN_AND_MEAN
#define WINDOWS_IGNORE_PACKING_MISMATCH
#define NOMINMAX
#define _CRT_SECURE_NO_WARNINGS
#include <windows.h>

#define INI_FILE ".\\eqclientmod.ini"

#define BUILD_VERSION "SOLAR_TITANIUM_2025081400"

#define COMMAND_HANDLER
#define TIMER_HACK
#define GAMMA_HACK
#define QEYNOS_CITIZEN_FEMALE_MODEL_HACK
#define SLEEP_REMOVER_HACK
#define PROGRAM_LAUNCH_HACK
#define ZONE_VERSION_HACK
//#define DEV_HACK
#define WINDOW_TITLE_HACK
